//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceGray.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceGray.Core.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copied to clipboard.
        /// </summary>
        public static string BarCopiedToClipboard {
            get {
                return ResourceManager.GetString("BarCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ButtonBack {
            get {
                return ResourceManager.GetString("ButtonBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string ButtonColor {
            get {
                return ResourceManager.GetString("ButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ButtonError {
            get {
                return ResourceManager.GetString("ButtonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string ButtonGray {
            get {
                return ResourceManager.GetString("ButtonGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string ButtonInfo {
            get {
                return ResourceManager.GetString("ButtonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less.
        /// </summary>
        public static string ButtonLess {
            get {
                return ResourceManager.GetString("ButtonLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string ButtonMark {
            get {
                return ResourceManager.GetString("ButtonMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string ButtonMore {
            get {
                return ResourceManager.GetString("ButtonMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string ButtonOpen {
            get {
                return ResourceManager.GetString("ButtonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek.
        /// </summary>
        public static string ButtonSeek {
            get {
                return ResourceManager.GetString("ButtonSeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processing....
        /// </summary>
        public static string FormTextProcessing {
            get {
                return ResourceManager.GetString("FormTextProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains only white spaces, contains invalid characters or empty.
        /// </summary>
        public static string ReportArgument {
            get {
                return ResourceManager.GetString("ReportArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change event occurred on unaccessed path.
        /// </summary>
        public static string ReportChangeEventOnUnaccessedPath {
            get {
                return ResourceManager.GetString("ReportChangeEventOnUnaccessedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory path being on an unmapped drive, or the directory cannot be found.
        /// </summary>
        public static string ReportDirectoryNotFound {
            get {
                return ResourceManager.GetString("ReportDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse name in 8.3 format.
        /// </summary>
        public static string ReportEightDotThreeName {
            get {
                return ResourceManager.GetString("ReportEightDotThreeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to access path.
        /// </summary>
        public static string ReportEnumerateIO {
            get {
                return ResourceManager.GetString("ReportEnumerateIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path being on an unmapped drive, or the file cannot be found.
        /// </summary>
        public static string ReportFileNotFound {
            get {
                return ResourceManager.GetString("ReportFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains a colon (:) in the middle of the string.
        /// </summary>
        public static string ReportFileNotSupported {
            get {
                return ResourceManager.GetString("ReportFileNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote connection lost or internal buffer is overflowed.
        /// </summary>
        public static string ReportFileSystemWatcherErrorMessage {
            get {
                return ResourceManager.GetString("ReportFileSystemWatcherErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to continue monitoring file system changes.
        /// </summary>
        public static string ReportFileSystemWatcherErrorTitle {
            get {
                return ResourceManager.GetString("ReportFileSystemWatcherErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file is being used by another process.
        /// </summary>
        public static string ReportGetAttributesIO {
            get {
                return ResourceManager.GetString("ReportGetAttributesIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path exceed the system-defined maximum length.
        /// </summary>
        public static string ReportPathTooLong {
            get {
                return ResourceManager.GetString("ReportPathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect new name of renamed path.
        /// </summary>
        public static string ReportRenamedNewPathIsUnknown {
            get {
                return ResourceManager.GetString("ReportRenamedNewPathIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect previous name of renamed path.
        /// </summary>
        public static string ReportRenamedOldPathIsUnknown {
            get {
                return ResourceManager.GetString("ReportRenamedOldPathIsUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root child with name one symbol long is missing.
        /// </summary>
        public static string ReportRootChildOneSymbolLong {
            get {
                return ResourceManager.GetString("ReportRootChildOneSymbolLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No access permissions.
        /// </summary>
        public static string ReportSecurity {
            get {
                return ResourceManager.GetString("ReportSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating system denied access.
        /// </summary>
        public static string ReportUnauthorizedAccess {
            get {
                return ResourceManager.GetString("ReportUnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string SeverityError {
            get {
                return ResourceManager.GetString("SeverityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string SeverityInfo {
            get {
                return ResourceManager.GetString("SeverityInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string SeverityWarning {
            get {
                return ResourceManager.GetString("SeverityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string SizeByte {
            get {
                return ResourceManager.GetString("SizeByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EB.
        /// </summary>
        public static string SizeExabyte {
            get {
                return ResourceManager.GetString("SizeExabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string SizeGigabyte {
            get {
                return ResourceManager.GetString("SizeGigabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string SizeKilobyte {
            get {
                return ResourceManager.GetString("SizeKilobyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string SizeMegabyte {
            get {
                return ResourceManager.GetString("SizeMegabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PB.
        /// </summary>
        public static string SizePetabyte {
            get {
                return ResourceManager.GetString("SizePetabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        public static string SizeTerabyte {
            get {
                return ResourceManager.GetString("SizeTerabyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to • Click Open button to explore a folder
        ///• Double click on file to open containing folder in Explorer
        ///• Double click on folder to display it
        ///
        ///• Use Less and More buttons to increase and decrease detalization
        ///• The Color button toggles drawing in gray and color modes
        ///
        ///• Right click on file or folder to hide it
        ///• Click Mark button to display hidden nodes
        ///
        ///© SpaceGray by Gologames.
        /// </summary>
        public static string TabInfo {
            get {
                return ResourceManager.GetString("TabInfo", resourceCulture);
            }
        }
    }
}
